"""added post id to stuff

Revision ID: 5790a1880e10
Revises: d0a7cd563bf7
Create Date: 2020-05-06 09:24:25.797190

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5790a1880e10'
down_revision = 'd0a7cd563bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_share', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post_share', 'post', ['post_id'], ['id'])
    op.add_column('post_view', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post_view', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_view', type_='foreignkey')
    op.drop_column('post_view', 'post_id')
    op.drop_constraint(None, 'post_share', type_='foreignkey')
    op.drop_column('post_share', 'post_id')
    # ### end Alembic commands ###
