"""Added user_id

Revision ID: 610d927bf704
Revises: dcc3b86a2c6c
Create Date: 2020-04-28 15:23:21.750851

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '610d927bf704'
down_revision = 'dcc3b86a2c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'admin', 'user', ['user_id'], ['id'])
    op.add_column('client', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'])
    op.add_column('vendor', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'vendor', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendor', type_='foreignkey')
    op.drop_column('vendor', 'user_id')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'user_id')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_column('admin', 'user_id')
    # ### end Alembic commands ###
