"""added last login

Revision ID: 67181109311c
Revises: 863d285d5211
Create Date: 2020-05-06 21:09:46.038436

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '67181109311c'
down_revision = '863d285d5211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'last_login')
    # ### end Alembic commands ###
