"""Created Settings

Revision ID: 86d8cc11ea8b
Revises: 610d927bf704
Create Date: 2020-04-29 01:12:47.511345

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '86d8cc11ea8b'
down_revision = '610d927bf704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('read_news', sa.Float(), nullable=True),
    sa.Column('comment', sa.Float(), nullable=True),
    sa.Column('share_news', sa.Float(), nullable=True),
    sa.Column('login_bonus', sa.Float(), nullable=True),
    sa.Column('share_daily_sponsored', sa.Float(), nullable=True),
    sa.Column('share_daily_advert', sa.Float(), nullable=True),
    sa.Column('referral_bonus', sa.Float(), nullable=True),
    sa.Column('testimonies_bonus', sa.Float(), nullable=True),
    sa.Column('min_withdrawal_limit', sa.Float(), nullable=True),
    sa.Column('max_withdrawal_limit', sa.Float(), nullable=True),
    sa.Column('sign_up_fee', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
