"""Actually just Fixed refferal in client

Revision ID: ac834ed81d12
Revises: f09430767c81
Create Date: 2020-05-03 16:22:12.084063

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ac834ed81d12'
down_revision = 'f09430767c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('referral_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client', 'client', ['referral_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'referral_id')
    # ### end Alembic commands ###
