"""SET TO NULL referral ID

Revision ID: b77fe47aa226
Revises: ac834ed81d12
Create Date: 2020-05-03 16:29:54.358664

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b77fe47aa226'
down_revision = 'ac834ed81d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_ibfk_2', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'client', ['referral_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_ibfk_2', 'client', 'client', ['referral_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
