"""Modifed Comment

Revision ID: d0a7cd563bf7
Revises: b77fe47aa226
Create Date: 2020-05-05 23:47:35.644567

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd0a7cd563bf7'
down_revision = 'b77fe47aa226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('valid', sa.Boolean(), nullable=True))
    op.drop_constraint('comment_ibfk_3', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_3', 'comment', 'client', ['post_id'], ['id'])
    op.drop_column('comment', 'valid')
    # ### end Alembic commands ###
