"""Added Activity Ids

Revision ID: dcc3b86a2c6c
Revises: 329c181502fe
Create Date: 2020-04-28 14:54:10.019631

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcc3b86a2c6c'
down_revision = '329c181502fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comment', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('comment', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'comment', 'activity', ['activity_id'], ['id'])
    op.create_foreign_key(None, 'comment', 'client', ['post_id'], ['id'])
    op.alter_column('post', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'post', 'category', ['category_id'], ['id'])
    op.alter_column('post_share', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'post_share', 'activity', ['activity_id'], ['id'])
    op.alter_column('post_view', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'post_view', 'activity', ['activity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_view', type_='foreignkey')
    op.alter_column('post_view', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'post_share', type_='foreignkey')
    op.alter_column('post_share', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.alter_column('post', 'category_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.alter_column('comment', 'post_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('comment', 'activity_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
