"""Created Settings sign up bonus

Revision ID: dd8f978c9d5f
Revises: 86d8cc11ea8b
Create Date: 2020-04-29 01:37:11.683889

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'dd8f978c9d5f'
down_revision = '86d8cc11ea8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('setting', sa.Column('sign_up_bonus', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('setting', 'sign_up_bonus')
    # ### end Alembic commands ###
