"""Fixed refferal in client

Revision ID: f09430767c81
Revises: 4ae5c5614010
Create Date: 2020-05-03 16:21:43.901309

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f09430767c81'
down_revision = '4ae5c5614010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_ibfk_2', 'client', type_='foreignkey')
    op.drop_column('client', 'referral_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('referral_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('client_ibfk_2', 'client', 'category', ['referral_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
